Adding some instructions for IntelliJ and Maven
gurkenlabs/litiengine-docs pull request #18
Opened 2022-06-19 14:54 UTC by ghostcrafter551

I changed some files to include instructions for IntelliJ IDEA and Maven as a build system.
I also recommended [SDKMAN!](https://sdkman.io/) to manage Java JREs, build tools and other Java related stuff.

2022-06-19 21:11 UTC, nightm4re94 requested changes
Thanks for elaborating these topics!
I've proposed a few changes, please apply those.
Also, right now, we store all images in the images directory on top level. Not saying this is optimal, but please follow that structure and put all images in [`images`](https://github.com/gurkenlabs/litiengine-docs/tree/master/images).

2022-06-19 21:11 UTC, nightm4re94 commented on getting-started/install-jdk.md
> +> If you're on linux or mac, I would hightly recommend to use [SKDMAN!](https://sdkman.io/). If you installed sdk man, type `sdk install java` in your terminal. The latest recommend JDK will be insta
```suggestion
> If you're on linux or mac, we recommend using [SKDMAN!](https://sdkman.io/). If you installed sdk man, type `sdk install java` in your terminal. The latest recommend JDK will be installed automatically for you. It should be registered in your IDE after you restart it. For further information look up the [SDKMAN! Docs](https://sdkman.io/usage).
```

2022-06-19 21:11 UTC, nightm4re94 commented on getting-started/development-environment.md
> +> If you're on linux or mac, I would hightly recommend to use [SKDMAN!](https://sdkman.io/). If you installed sdk man, type `sdk install java` in your terminal. The latest recommend JDK will be insta
```suggestion
> If you're on linux or mac, you can also use [SDKMAN!](https://sdkman.io/) to manage your JDK installation. If you installed sdk man, type `sdk install java` in your terminal. The latest recommend JDK will be installed automatically for you. It should be registered in your IDE after you restart it. For further information look up the [SDKMAN! Docs](https://sdkman.io/usage).
```

2022-06-19 21:11 UTC, nightm4re94 commented on getting-started/development-environment.md
> +To make shure the JDK got installed correctly, open the `New Project` dialogue and expand the `JDK` dropdown menu. If you see your installed JDK in the list, you're set. If you don't, you have to cli
```suggestion
To make sure the JDK got installed correctly, open the `New Project` dialogue and expand the `JDK` dropdown menu. If you see your installed JDK in the list, you're set. If you don't, you have to click on the `Add JDK...` button. A file picker dialogue will open, choose your JDK folder there.
```

2022-06-19 21:11 UTC, nightm4re94 commented on getting-started/build-systems.md
> +> If you're on linux or mac, I would hightly recommend to use [SKDMAN!](https://sdkman.io/). If you installed SDKMAN!, type `sdk install gradle` in your terminal. The latest recommend version of Grad
```suggestion
> If you're on linux or mac, you can also use [SDKMAN!](https://sdkman.io/) to manage your Gradle installation. If you installed SDKMAN!, type `sdk install gradle` in your terminal. The latest recommend version of Gradle will be installed automatically for you. It should be registered in your IDE after you restart it. For further information look up the [SDKMAN! Docs](https://sdkman.io/usage). **If you use SDKMAN! skip the next three steps**.
```

2022-06-19 21:11 UTC, nightm4re94 commented on getting-started/build-systems.md
> +> If you're on linux or mac, I would hightly recommend to use [SKDMAN!](https://sdkman.io/). If you installed SDKMAN!, type `sdk install maven` in your terminal. The latest recommend version of Maven
```suggestion
> If you're on linux or mac, you can also use [SDKMAN!](https://sdkman.io/) to manage your Maven installation. If you installed SDKMAN!, type `sdk install maven` in your terminal. The latest recommend version of Maven will be installed automatically for you. It should be registered in your IDE after you restart it. For further information look up the [SDKMAN! Docs](https://sdkman.io/usage). **If you use SDKMAN! skip the next three steps**.
```

2022-06-20 15:08 UTC, ghostcrafter551 commented on getting-started/build-systems.md
> +* [download Gradle](https://gradle.org/install/).
IntelliJ already uses a wrapper automatically so the installation of gradle (or maven) is obsolete. I added information about that in my new pr

2022-06-24 18:38 UTC, nightm4re94 commented on getting-started/build-systems.md
> +> If you're on linux or mac, you can also use [SKDMAN!](https://sdkman.io/) to manage your Gradle installation. As soon you installed SDKMAN!, type `sdk install gradle` in your terminal. The latest r
```suggestion
> If you're on linux or mac, you can also use [SKDMAN!](https://sdkman.io/) to manage your Gradle installation. Once you installed SDKMAN!, type `sdk install gradle` in your terminal. The latest recommend version of Gradle will be installed automatically for you. It should be registered in your IDE after you restart it. For further information look up the [SDKMAN! Docs](https://sdkman.io/usage). **In case you use SDKMAN! skip the next three steps**.
```

2022-06-24 18:39 UTC, nightm4re94 commented on getting-started/build-systems.md
> +> If you're on linux or mac, you can also use [SKDMAN!](https://sdkman.io/) to manage your Maven installation. As soon you installed SDKMAN!, type `sdk install maven` in your terminal. The latest rec
```suggestion
> If you're on linux or mac, you can also use [SKDMAN!](https://sdkman.io/) to manage your Maven installation. Once you've installed SDKMAN!, type `sdk install maven` in your terminal. The latest recommend version of Maven will be installed automatically for you. It should be registered in your IDE after you restart it. For further information look up the [SDKMAN! Docs](https://sdkman.io/usage). **In case you use SDKMAN! skip the next three steps**.
```

2022-06-24 18:39 UTC, nightm4re94 commented on getting-started/development-environment.md
> +> If you're on linux or mac, you can also use [SKDMAN!](https://sdkman.io/) to manager your JDK installation . As soon you installed sdk man, type `sdk install java` in your terminal. The latest reco
```suggestion
> If you're on linux or mac, you can also use [SKDMAN!](https://sdkman.io/) to manager your JDK installation . Once you've installed sdk man, type `sdk install java` in your terminal. The latest recommend JDK will be installed automatically for you. It should be registered in your IDE after you restart it. For further information look up the [SDKMAN! Docs](https://sdkman.io/usage).
```

2022-06-24 18:39 UTC, nightm4re94 commented on getting-started/install-jdk.md
> +> In case you are on linux or mac, you can also use [SKDMAN!](https://sdkman.io/) to manager your JDK installation. As soon you installed sdk man, type `sdk install java` in your terminal. The latest
```suggestion
> In case you are on linux or mac, you can also use [SKDMAN!](https://sdkman.io/) to manager your JDK installation. Once you've installed sdk man, type `sdk install java` in your terminal. The latest recommend JDK will be installed automatically for you. It should be registered in your IDE after you restart it. For further information look up the [SDKMAN! Docs](https://sdkman.io/usage).
```

2022-06-24 18:40 UTC, nightm4re94 approved these changes

2022-06-24 18:41 UTC, merged