Edition on litiengine-docs
gurkenlabs/litiengine-docs pull request #9
Opened 2020-12-07 11:51 UTC by kara9504

Hello! 

Our project team wanted to help on litiengine-docs so we filled some more materials on getting-started, input api, and tutorial for litiengine-ldjam44. We thought litiengine provides great library and map editor but thought it's quite a shame that other newbies interested in 2D game development do not know about this wonderful open-source. Our goal was to make beginners better understand on you libraries and map editor. Hope you guys like our edits and wish this didn't bother you. We'll be expect your affirmative reply. 
Thank you! Have a nice day!

2020-12-07 14:44 UTC, nightm4re94 commented on tutorials/trying-an-example.md
> +```html
this is xml, but should't really matter in this case.

2020-12-07 14:45 UTC, nightm4re94 commented on tutorials/trying-an-example.md
> +SERVUS BONUS is a 2D game made by Steffen with Litienine. Steffen's github address is https://github.com/steffen-wilke. Currently, it is provided with the MIT license, so it can be modified freely.
Words hurt :( The game was made by both of us!

2020-12-07 14:48 UTC, nightm4re94 commented on tutorials/trying-an-example.md
> +
typo: LITIENGINE (which should also be capitalized on every occasion)

2020-12-07 14:51 UTC, nightm4re94 commented on tutorials/trying-an-example.md
> +Editting icon itself is also delivered by the utiLITI readily. Figure shown below show this well. Icons seem active by giving spritewidth and spriteheight a proper value. Also duration contributes fo
I think the wording here is a bit confusing: Maybe talk about spritesheets and sprite images instead of icons?

2020-12-07 14:56 UTC, nightm4re94 requested changes
Hey there, thank you for all the effort you've put into this!
I have added some comments where tiny changes should be made, but all in all this guide is very helpful. 
Please make sure that

- LITIENGINE is capitalized and written as one word
- your GIFs feature a clear resolution without artifacts. (We have often used ScreenToGif for this task, which is configurable in terms of compression and file size)

Also, as [mentioned on your previous PR](https://github.com/gurkenlabs/litiengine-docs/pull/8#discussion_r537031327), an overview over available JDK vendors would be helpful.

2020-12-10 14:19 UTC, Susoon commented
Hello. I am another member of the team that sent me the previous pull request. We've corrected all the amendments you mentioned. Sorry for not putting your name in the developer of SERVUS BONUS. There was a lack of preliminary research. Please check the commit details. Thank you.

2020-12-30 14:58 UTC, nightm4re94 approved these changes

2020-12-30 14:59 UTC, merged